# Generated by Django 5.2.1 on 2025-05-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='bairro',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
