# Generated by Django 5.1.2 on 2025-05-20 14:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_bairro'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
