# Generated by Django 5.2.1 on 2025-05-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_criado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='latencia',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
